### PR TITLE
Patchable commit

### PR DESCRIPTION
**Pull request by jung-kim**
So this is something I have been hacking off and on and I have ran into a problem and I was hoping if you have any suggestions.

https://github.com/FredrikNoren/ungit/issues/169

Big problem is at the very last commit, `git.js`.  Before this, all child process we spawn are straight forward and we didn't need an interactions with it.  However now with this `git add --patch` we would have to interactively response to input and output.  Last commit was my initial attempt at solve this issue.

However stdoutListerner callback is never called.  callback is called if I change  https://github.com/campersau/ungit/commit/3509bfcbe158eeab66f84b5a85b04be5b3d13d87#diff-3d97d6a0bc43fe2abcbb34e038981c44R358 to 'status' this works fine.  

Do you have any suggestions?

### CODE REVIEW

**Comment by campersau** [comment]
Hi @codingtwinky,

I haven't had time to look at the code yet but here are some general thoughts about this feature:

I have also looked for a method to only include selected lines in a commit and I think that `git add -p` is quit complex to use. (Sending and reading to / from a process and accepting / rejecting each diff hunk individually.)
Another method might be to use [`git apply`](http://git-scm.com/docs/git-apply) where you can apply diffs which could be generated by `git diff -U0` and removing the unchecked lines.
Note: I haven't checked if this does actually work but it might be easier to implement.

I try to look at your code tomorrow (in germany it is night already).

**Comment by jung-kim** [comment]
This definitely an ambitious feature I will venture into `git apply`  and update it as we go.

it would be nice as this and undo seems to be the most desired features.

**Comment by campersau** [comment]
Just for reference: I looked at the source code of git and found that they also use `git apply` via [`git diff` / `git diff-files`](https://github.com/git/git/blob/3188ab3af60df6ace996d3985e8f1ca1ed3cbda5/git-add--interactive.perl#L100-L119) in `git add -p`

**Comment by campersau** [comment]
@codingtwinky I have the same problem using `child_process.spawn` with stdout listeners. Maybe they are attached too late because when using a file pipe it does work:

``` js
var fs = require("fs");
var child_process = require("child_process");

var gitPatch = child_process.spawn("git", [ "add", "-p" ], {
    stdio: [
      'pipe', // use parents stdin for child
      fs.openSync("stdout.txt", "w"), // direct child's stdout to file
      fs.openSync("stderr.txt", "w") // direct child's stderr to a file
    ]
});
```

After running this `stdout.txt` contains the text from the first diff or `stderr.txt` contains `No changes` if no changes were detected.
But I have currently no idea how to fix this...

So if `git apply` works for us we do not have to deal with this issue :smirk:

**Comment by jung-kim** [comment]
I did some digging around git api and I'm not sure what would be easier despite knowing `git add --patch` is a pain.

we would have to do git apply after commit is [done](https://github.com/codingtwinky/ungit/blob/patch/source/git.js#L395) and what is being applied is in stash.  Because git apply brings diff to staging not to commit so we will get merge conflicts if we were to do this at [here](https://github.com/codingtwinky/ungit/blob/patch/source/git.js#L355) right?  So we would have to do this if we were to use `git apply` to prevent conflict and etc...
1. add all files to be added via `git update-index`
2. remove all files to be removed via `git update-index`
3. commit
4. create two different diffs from existing diff: one user selected to be committed, one to be remain in staging.
5. stash all
6. apply diff what user want to be committed
7. amend to commit
8. apply diff to be remain in staging.
9. if successful, remove latest stash if not disregard all diff and pop from stash

If `git apply` can amend straight to latest commit or `git update-index` to apply patch this would be much easier but I don't know if that is possible.  I guess this would be OS independent then interactively working with vi and git through spawned process programmatically...

or am i totally missing something?

cc @FredrikNoren @Ajedi32

**Comment by Ajedi32** [comment]
Hmm, so I'm not entirely sure I understand the process you're using there. For 1 and 2, any reason why you're not just using `git add`/`git rm`? For 4, what do you mean by "remain in staging"? I thought ungit's current UI doesn't expose the staging area, does this PR change that? For 6, wouldn't you want to apply the inverse of the diff of what the user _doesn't_ want commited, since you already committed all changes, and you're just modifying that commit?

Anyway, this seems pretty convoluted. My suggestion for allowing adding partial commits would be to use `git add --edit` with the `GIT_EDITOR` environment variable set to some process that ungit controls. You could have that process edit the files as needed, then when the process terminates git will do the rest.

**Comment by jung-kim** [comment]
Usage of `update-index` instead of `add` and `rm` is a left over hangover from old code, we could definitely replace it but not sure if this will give us any old git compatibility advantage.  

For 4, I mean to be uncommitted and remain modified.  This pr doesn't introduce staging to ungit

For 6,  no because patched commit hasn't been committed, only changes that are committed by 6 is the non partial changes.  patched partial changes hasn't been committed yet.  `update-index` doesn't support patches.

Will look up on `git add --edit` but it seems much more easier to work with

**Comment by jung-kim** [comment]
So I think I can do this via, get the result of `git diff`, modify the result based on user's input, and paste in the modified result to `git add -e`.  This will be tricky...

**Comment by campersau** [comment]
Yes, that was exactly what I thought that `git apply` would do.
From [`git add --edit`](https://git-scm.com/docs/git-add) documentation:

> Open the diff vs. the index in an editor and let the user edit it. After the editor was closed, adjust the hunk headers and **apply the patch to the index**.

**Comment by jung-kim** [comment]
One great thing about `apply` is that it can read from a .patch file and apply it.  However I don't think `add` has anything like that.  I would have to use git's text editor.  Are you guys aware of a way to use `git add -e` to read from a file?

**Comment by Ajedi32** [comment]
@campersau `git apply` can definitely be used to just apply patches to the index if you want. Just use the [`--cached` option](https://www.kernel.org/pub/software/scm/git/docs/git-apply.html):

> **`--cached`**
> 
> Apply a patch without touching the working tree. Instead take the cached data, apply the patch, and store the result in the index without using the working tree. This implies `--index`.

**Comment by jung-kim** [comment]
So... it works...   to my utter surprise...  there are edge cases that I would have to test out and add to test suite but simple case works... 

Here are things left to do:
- [ ] fix vi piping
- [ ] add unit tests for parser
- [ ] add click test
- [ ] fix front end diff refreshing on patch commit
- [ ] support for windows
- [ ] performance (?)

**Comment by jung-kim** [comment]
@Ajedi32 hey could you elaborate more on using `git apply --cached`?  it's output is different, not only for the included mail header but diff syntax seems to be different the `git diff`.  And even when `git diff -U3` it didn't work.  

Also, problem with git apply is it does not remove indexed diffs from current diff.  so we would have to calculate the two different diffs, one to be committed and one to be remain uncommitted.

**Comment by Ajedi32** [comment]
You definitely can use `git diff` with `git apply`. Try the following with unstaged changes in your working directory:

```
git add -AN # Needed for handling untracked files
git diff | git apply --cached
git status
```

My assumption is that you should be able to edit the output from git diff in order to get the patch you want. I certainly could be wrong though.

**Pull request closed without merging**
